/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalContent: typeof import('@/components/Content.vue')['default']
    ModalWindow: typeof import('@/components/Modal.vue')['default']
    SendButton: typeof import('@/components/Button.vue')['default']
  }
}
